import { MarketingPage } from "../marketing-shell";

const blocks = [
  ["Kontaktformular auf der Homepage", "Das Formular übermittelt Name, E-Mail-Adresse, optional Telefonnummer, gewünschtes Angebot und Nachricht an unsere geschützte Verwaltung in Supabase. Berechtigte Administratoren bearbeiten die Anfrage mit internen Notizen und Status. Die Daten dienen der Beantwortung und gegebenenfalls Vertragsvorbereitung (Art. 6 Abs. 1 lit. b DSGVO). Es erfolgt keine Newsletter-Anmeldung. Zur Missbrauchsbegrenzung verwenden wir zusätzlich nicht direkt lesbare, mit einem geheimen Schlüssel abgeleitete Kennungen aus IP-Adresse und E-Mail-Adresse sowie zeitlich begrenzte Anfragezähler (berechtigtes Interesse, Art. 6 Abs. 1 lit. f DSGVO). Diese Zähler werden bei der nächsten Formularverarbeitung nach Ablauf von 48 Stunden bereinigt; sie enthalten keinen Nachrichtentext."],
  ["Verantwortlicher", "POTLOG Immobilien KG, Aufeldstraße 21, 4050 Traun, Österreich. Kontakt für Datenschutzanfragen: roland@immo-kredit.net, +43 664 35 17 810. Diese Hinweise gelten für aufeld21.at und das zugehörige Mitgliederportal."],
  ["Website und technische Sicherheit", "Beim Aufruf verarbeitet unser Hosting-Anbieter Vercel insbesondere IP-Adresse, Zeitpunkt, angeforderte Inhalte sowie Browser- und Geräteinformationen. Zweck ist die Auslieferung und Absicherung der Website, einschließlich Fehler- und Missbrauchserkennung. Grundlage ist unser berechtigtes Interesse an einem sicheren, funktionsfähigen Angebot (Art. 6 Abs. 1 lit. f DSGVO)."],
  ["Anfragen per E-Mail, Telefon oder WhatsApp", "Wir verarbeiten Ihre Kontaktdaten und den Inhalt Ihrer Anfrage, um zu antworten und gegebenenfalls einen Vertrag vorzubereiten (Art. 6 Abs. 1 lit. b DSGVO); sonst zur Bearbeitung berechtigter Anliegen (lit. f). Der E-Mail-Button öffnet Ihr Mailprogramm. WhatsApp ist nur verlinkt und wird erst beim Anklicken geöffnet. Dann gelten zusätzlich die Datenschutzbedingungen von WhatsApp. Sie können uns alternativ per E-Mail oder Telefon kontaktieren."],
  ["Mitgliederportal und Verwaltung", "Für Anmeldung, Buchungen, Vertrags- und Rechnungsverwaltung verwenden wir Supabase. Verarbeitet werden Name, freigeschaltete E-Mail-Adresse, Authentifizierungsdaten, Unternehmens- und Abrechnungsdaten, Vertragsunterlagen, Buchungen, Stundenkontingente, Zahlungsvermerke und gegebenenfalls ausgegebene Schlüssel oder Chips. Die Daten erhalten wir von Ihnen oder der zuständigen Verwaltung. Sie dienen der Vertragsabwicklung (Art. 6 Abs. 1 lit. b DSGVO), gesetzlichen Pflichten (lit. c) und der sicheren Organisation des Betriebs (lit. f). Ohne notwendige Konto- und Vertragsdaten kann das Portal nicht bereitgestellt werden. Andere Mitglieder können zur Raumplanung die Belegung und zugehörige Namen sehen, nicht Ihre Rechnungen oder Verträge."],
  ["Meldungen aus dem Space", "Wenn Sie ein Problem melden, speichern wir die Angaben mit Ihrem Konto und dem Bearbeitungsstatus. Die zuständige Verwaltung kann diese Meldungen bearbeiten. Zweck ist die Organisation, Sicherheit und Instandhaltung des Spaces auf Grundlage des Vertrags und unseres berechtigten Interesses am geordneten Betrieb (Art. 6 Abs. 1 lit. b bzw. f DSGVO). Bitte geben Sie keine unnötigen vertraulichen Angaben über Dritte ein."],
  ["Notwendige E-Mails", "Für Einladungen, Passwort-Mails und Portalhinweise nutzen wir Resend. Dabei werden Empfängeradresse, notwendiger Nachrichteninhalt sowie technische Versand- und Zustelldaten verarbeitet. Die E-Mails unterstützen Anmeldung und Vertragsabwicklung (Art. 6 Abs. 1 lit. b bzw. f DSGVO). Rechnungshinweise verlinken auf das geschützte Portal, ohne Rechnungsanhang. Meldungshinweise an die Verwaltung enthalten keinen Meldungstext. Ein Werbe-Newsletter wird darüber nicht versendet."],
  ["Freiwillige Geräte-Benachrichtigungen", "Nur die freigeschalteten Verwaltungskonten von Julia und Roland können Web-Push je Gerät ausdrücklich erlauben (Art. 6 Abs. 1 lit. a DSGVO). Gespeichert werden die technische Abonnementadresse und Verschlüsselungsschlüssel. Die Zustellung erfolgt über den Pushdienst des Browsers, beispielsweise Apple oder Google. Der Sperrbildschirm zeigt keine vertraulichen Meldungsinhalte. Sie können die Einwilligung für die Zukunft im Portal oder in den Geräteeinstellungen widerrufen; die bisherige Verarbeitung bleibt davon unberührt. Beim Abmelden wird dieses Gerät getrennt. Ohne Push bleiben Portal und E-Mail nutzbar."],
  ["Cookies und Gerätespeicher", "Wir setzen keine eigenen Analyse- oder Werbetracker ein. Im Portal werden technisch notwendige Anmelde-Cookies verwendet. Im lokalen Gerätespeicher merken wir uns außerdem, welchen Rechnungshinweis Sie bereits gesehen haben. Freiwilliges Push verwendet einen Service Worker und einen kleinen Speicher zur Vermeidung doppelter Hinweise; Portal-Seiten und Rechnungsdateien werden nicht für eine Offline-Nutzung gespeichert. Gerätespeicher kann über die Browsereinstellungen gelöscht werden; dann kann eine erneute Anmeldung erforderlich sein."],
  ["Empfänger und Übermittlungen", "Berechtigte Verwaltungsmitarbeiter erhalten Zugriff, soweit dies zur Betreuung erforderlich ist. Technische Dienstleister sind Vercel Inc. für Hosting, Supabase Pte. Ltd. für Authentifizierung, Datenbank und Dokumentenspeicher sowie Resend (Plus Five Five, Inc.) für Versand. Das Supabase-Projekt nutzt die Region Frankfurt. Das schließt weitere Verarbeitung durch Dienstleister außerhalb des EWR, etwa in den USA oder Singapur, nicht aus. Die unten verlinkten Auftragsverarbeitungsbedingungen enthalten insbesondere EU-Standardvertragsklauseln als Garantien für entsprechende Übermittlungen. Informationen zu den eingesetzten Garantien erhalten Sie auch über unseren Datenschutzkontakt."],
  ["Speicherdauer", "Anfragen und Verwaltungsdaten werden so lange benötigt, wie die Bearbeitung, das Vertragsverhältnis oder die Abwicklung offener Ansprüche dies erfordern. Für Rechnungen und steuerlich relevante Unterlagen gelten gesetzliche Aufbewahrungspflichten; solche Unterlagen werden nicht allein durch das Deaktivieren eines Portalzugangs gelöscht. Technische Protokolle dienen der zeitlich erforderlichen Fehler- und Sicherheitsprüfung. Nicht mehr benötigte Daten sind zu löschen, soweit keine Aufbewahrungspflicht oder Rechtsverteidigung entgegensteht."],
  ["Ihre Rechte", "Nach den gesetzlichen Voraussetzungen haben Sie Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung und Datenübertragbarkeit. Bei Verarbeitung auf Grundlage berechtigter Interessen können Sie aus Gründen Ihrer besonderen Situation widersprechen. Einwilligungen können Sie jederzeit mit Wirkung für die Zukunft widerrufen. Wenden Sie sich dazu an unseren Datenschutzkontakt. Sie können außerdem Beschwerde bei der Österreichischen Datenschutzbehörde erheben: Barichgasse 40–42, 1030 Wien, dsb@dsb.gv.at. Es erfolgt keine ausschließlich automatisierte Entscheidung mit rechtlicher oder ähnlich erheblicher Wirkung; Zahlungseingänge werden manuell bestätigt."],
];

export default function PrivacyPage() {
  return <MarketingPage eyebrow="Rechtliches" title="Datenschutz" intro="Welche Daten Website und Mitgliederportal benötigen – und welche Benachrichtigungen freiwillig sind.">
    <section className="mx-auto max-w-4xl px-5 pb-12 sm:px-8 lg:pb-16"><div className="space-y-7 rounded-[2rem] bg-white p-6 shadow-sm sm:p-10">
      {blocks.map(([title, text]) => <div key={title}><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 break-words leading-7 text-stone-600">{text}</p></div>)}
      <div><h2 className="text-xl font-bold">Weiterführende Informationen</h2><ul className="mt-3 space-y-2 text-stone-600">
        {[
          ["Vercel – Auftragsverarbeitung", "https://vercel.com/legal/dpa"],
          ["Supabase – Auftragsverarbeitung", "https://supabase.com/legal/customer-resources/data-processing-addendum"],
          ["Resend – Auftragsverarbeitung", "https://resend.com/legal/dpa"],
          ["WhatsApp – Datenschutz", "https://www.whatsapp.com/legal/privacy-policy-eea"],
          ["Österreichische Datenschutzbehörde", "https://dsb.gv.at/rechte-pflichten/ihre-rechte-als-betroffene-person"],
        ].map(([label, href]) => <li key={href}><a className="inline-flex min-h-11 items-center underline underline-offset-4" href={href}>{label}</a></li>)}
      </ul></div>
      <p className="border-t border-stone-200 pt-5 text-sm text-stone-500">Stand: 7. September 2026</p>
    </div></section>
  </MarketingPage>;
}
