import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MarketingHeader, MarketingFooter } from "@/app/homepage-preview/marketing-shell";
import { blogPosts } from "@/lib/blog";
import { siteUrl } from "@/lib/site";
type Props = {params:Promise<{slug:string}>};
export const dynamicParams = false;
export function generateStaticParams(){return blogPosts.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const p=blogPosts.find(p=>p.slug===slug);if(!p)return {};return {title:p.title,description:p.description,alternates:{canonical:`${siteUrl}/blog/${p.slug}`},openGraph:{title:p.title,description:p.description,type:"article",publishedTime:p.date,url:`${siteUrl}/blog/${p.slug}`,locale:"de_AT",siteName:"AUFELD21"}};}
export default async function BlogArticle({params}:Props){const {slug}=await params;const p=blogPosts.find(p=>p.slug===slug);if(!p)notFound();const structured={"@context":"https://schema.org","@type":"BlogPosting",headline:p.title,description:p.description,datePublished:p.date,author:{"@type":"Organization",name:"AUFELD21",url:siteUrl},publisher:{"@type":"Organization",name:"Potlog Immobilien KG"},mainEntityOfPage:`${siteUrl}/blog/${p.slug}`};return <main className="homepage-grid min-h-screen bg-[#f8f8fb] text-[#11131a]"><MarketingHeader/><article className="mx-auto max-w-3xl px-5 pb-16 pt-8 sm:px-8"><Link href="/blog" className="inline-flex min-h-11 items-center font-semibold text-emerald-800">← Alle Artikel</Link><p className="mt-8 text-xs font-bold uppercase tracking-widest text-emerald-800">{p.category}</p><h1 className="mt-4 text-[clamp(2rem,6vw,3.6rem)] font-semibold leading-tight tracking-[-0.04em]">{p.title}</h1><p className="mt-5 text-lg leading-8 text-stone-600">{p.description}</p><p className="mt-5 text-sm text-stone-500">AUFELD21 · <time dateTime={p.date}>{new Intl.DateTimeFormat("de-AT",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(p.date))}</time></p><div className="mt-10 space-y-9">{p.sections.map(s=><section key={s.heading}><h2 className="text-2xl font-semibold tracking-tight">{s.heading}</h2><p className="mt-3 text-base leading-8 text-stone-700">{s.text}</p></section>)}</div><aside className="mt-12 rounded-3xl bg-[#c9ff70] p-7"><h2 className="text-2xl font-semibold">Finde deinen Arbeitsplatz in Traun.</h2><p className="mt-3 leading-7">Wir zeigen dir persönlich die Räume und besprechen, welches Angebot zu deinem Alltag passt. Besichtigungen nach Vereinbarung.</p><Link href="/#contact" className="mt-5 inline-flex min-h-12 items-center rounded-full bg-[#162119] px-6 py-3 font-semibold text-white">Besichtigung anfragen →</Link><Link href={p.slug.includes("buero") ? "/buero-mieten-traun" : "/coworking-traun"} className="mt-3 flex min-h-11 items-center font-semibold">Aktuelle Angebote & Preise ansehen</Link></aside><nav aria-label="Weitere Artikel" className="mt-10 border-t border-stone-200 pt-6"><h2 className="text-lg font-semibold">Weiterlesen</h2>{blogPosts.filter(q=>q.slug!==p.slug).map(q=><Link key={q.slug} href={`/blog/${q.slug}`} className="mt-3 block py-2 text-emerald-800 underline underline-offset-4">{q.title}</Link>)}</nav></article><MarketingFooter/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}}/></main>}
