import Link from "next/link";
import { MarketingPage } from "./marketing-shell";
import { MarketingPrice } from "./marketing-price";
import { SpacePhoto } from "./space-photo";
import { ContactOfferLink } from "./contact-offer-link";
import { packages, officeArea } from "@/lib/members/packages";
import type { ContactSelectionKey } from "@/lib/contacts/selection";

export function WorkspaceOffer({ office = false }: { office?: boolean }) {
  const offers: { name: string; price: number; detail: string; key: ContactSelectionKey }[] = office
    ? [{ name: "Büro · 17 m²", price: 490, detail: "Ein eigener, abschließbarer Raum für konzentriertes Arbeiten.", key: "office-17" }, { name: `Büro · ${officeArea}`, price: packages.office.net, detail: "Mehr Platz für deinen Arbeitsalltag und ein kleines Team.", key: "office-25" }]
    : [{ name: "Flex-Platz", price: packages.flex.net, detail: "Freie Platzwahl im Coworking-Bereich – für alle, die keinen eigenen festen Tisch brauchen.", key: "flex" }, { name: "Fester Schreibtisch", price: packages.fix.net, detail: "Dein persönlicher Arbeitsplatz – für einen regelmäßigen Büroalltag außerhalb der eigenen vier Wände.", key: "fix" }];
  const faqs = office ? [
    ["Sind die Büros sofort verfügbar?", "Bitte frage deinen gewünschten Starttermin und die Personenzahl an. Welche Räume verfügbar sind und wie sie eingerichtet werden können, klären wir persönlich. Die Fotos zeigen Einblicke in unsere Räume, keine garantierte aktuelle Belegung."],
    ["Welche Laufzeit und Kaution gelten?", "Verfügbarkeit, Nutzerzahl, Laufzeit, Kündigungsfrist und gegebenenfalls Kaution vereinbaren wir vor Vertragsabschluss schriftlich. Bestehende individuelle Vereinbarungen bleiben unverändert."],
    ["Kann ich Kunden zu Besprechungen empfangen?", "Für Gespräche steht unser digital buchbarer Meetingraum zur Verfügung. Sieben Personen sitzen dort bequem. Zur Ausstattung gehören Fernseher, Kamera, Flipchart und ein elektrisches Samsung Smartboard."],
  ] : [
    ["Was ist der Unterschied zwischen Flex und Fix?", "Beim Flex-Platz wählst du deinen Arbeitsplatz im Coworking-Bereich frei. Beim Fix-Platz hast du deinen eigenen festen Schreibtisch. Beide Varianten nutzen die gemeinsame Infrastruktur."],
    ["Wann kann ich meinen Arbeitsplatz nutzen?", "Mitglieder haben rund um die Uhr Zugang per Chip. Für eine erste Besichtigung vereinbaren wir einen Termin, damit wir Zeit für dich und deine Fragen haben."],
    ["Ist Coworking auch für mich allein sinnvoll?", "Gerade wenn du selbstständig bist oder regelmäßig im Homeoffice arbeitest, kann ein Arbeitsplatz außerhalb der Wohnung helfen, Arbeit und Freizeit zu trennen. Bei einer Besichtigung kannst du prüfen, ob die Räume zu deinem Arbeitsalltag passen."],
  ];
  return <MarketingPage eyebrow="AUFELD21 · Traun Oedt" title={office ? "Büro mieten in Traun." : "Coworking in Traun."} intro={office ? "Dein eigener Raum mit gemeinsamer Infrastruktur: Entdecke unsere möblierten Büros in der Aufeldstraße 21 und frage die passende Größe für dich oder dein Team an." : "Raus aus dem Homeoffice, rein in deinen Arbeitsalltag: flexible Arbeitsplätze und feste Schreibtische in der Aufeldstraße 21 – mit Internet, Kaffee und Platz für Austausch."}>
    <section className="mx-auto grid max-w-[1440px] gap-8 px-5 pb-16 sm:px-8 lg:grid-cols-2 lg:px-12">
      <div className="flex flex-col justify-center rounded-3xl bg-[#162119] p-7 text-white sm:p-10"><h2 className="text-3xl font-semibold tracking-tight">{office ? "Eigene Tür. Alles Wichtige vor Ort." : "Laptop mitbringen. Ankommen. Arbeiten."}</h2><ul className="mt-6 space-y-3 leading-7">{["24/7-Zugang für Mitglieder per Chip", "Highspeed-Internet, Küche und kostenloser Kaffee", "Reinigung und gemeinsame Aufenthaltsbereiche", office ? "12 Meetingraum-Stunden gemeinsam je Büro / Monat" : "12 Meetingraum-Stunden je Person / Monat", "Persönlich geführt von Julia und Roland Potlog"].map(text => <li key={text}>✓ {text}</li>)}</ul><ContactOfferLink offer="visit" className="mt-8 inline-flex min-h-12 w-fit items-center rounded-full bg-[#c9ff70] px-6 py-3 font-bold text-[#162119]">Besichtigung anfragen →</ContactOfferLink><p className="mt-4 text-sm text-stone-300">Aufeldstraße 21 · 4050 Traun · Besichtigung nach Vereinbarung</p></div>
      <SpacePhoto photo={office ? "office" : "hallway"} priority caption sizes="(min-width: 1024px) 45vw, 100vw" className="overflow-hidden rounded-3xl border border-stone-200 bg-white" />
    </section>
    <section className="bg-[#eef0e9] px-5 py-14 sm:px-8"><div className="mx-auto max-w-5xl"><h2 className="text-3xl font-semibold tracking-tight">{office ? "Zwei Bürogrößen. Welcher Raum passt zu dir?" : "Welcher Arbeitsplatz passt zu deinem Alltag?"}</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{offers.map(offer => <article key={offer.key} className="flex flex-col rounded-3xl bg-white p-7 sm:p-9"><h3 className="text-xl font-bold">{offer.name}</h3><MarketingPrice net={offer.price} unit={office ? "für das gesamte Büro" : "pro Person"} /><p className="mb-7 mt-6 leading-7 text-stone-600">{offer.detail}</p><ContactOfferLink offer={offer.key} className="mt-auto inline-flex min-h-12 items-center justify-center rounded-full bg-[#162119] px-5 py-3 text-center font-semibold text-white">Verfügbarkeit anfragen</ContactOfferLink></article>)}</div><p className="mt-6 text-sm leading-6 text-stone-600">Verfügbarkeit und Vertragsdetails auf Anfrage. Kaffee ist inklusive; andere Getränke werden separat gemäß Preisliste vor Ort verrechnet. Zusätzliche Meetingraum-Zeit für Mitglieder: 12 € netto (14,40 € inkl. 20 % USt) pro Stunde, in 30-Minuten-Schritten. Nicht genutzte Inklusivstunden verfallen am Monatsende.{office && " Zusätzliche Logins im selben Büro teilen dessen Kontingent."}</p></div></section>
    <section className="mx-auto max-w-5xl px-5 py-14 sm:px-8"><h2 className="text-3xl font-semibold tracking-tight">Gut zu wissen</h2><div className="mt-6 divide-y divide-stone-200">{faqs.map(([question, answer]) => <div key={question} className="py-6"><h3 className="text-xl font-semibold">{question}</h3><p className="mt-3 leading-8 text-stone-600">{answer}</p></div>)}</div><div className="mt-8 rounded-3xl bg-[#c9ff70] p-7"><h2 className="text-2xl font-semibold">Schau dir AUFELD21 persönlich an.</h2><p className="mt-3 leading-7">Sag uns, wie du arbeitest, wie viele Plätze du brauchst und wann du starten möchtest. Gemeinsam finden wir heraus, welches Angebot passt.</p><ContactOfferLink offer="visit" className="mt-5 inline-flex min-h-12 items-center rounded-full bg-[#162119] px-6 py-3 font-semibold text-white">Besichtigung vereinbaren →</ContactOfferLink></div><Link href={office ? "/coworking-traun" : "/buero-mieten-traun"} className="mt-7 inline-flex min-h-11 items-center font-semibold text-emerald-800 underline underline-offset-4">{office ? "Lieber einen einzelnen Arbeitsplatz? Coworking ansehen" : "Mehr Privatsphäre? Unsere Büros ansehen"}</Link><Link href={office ? "/blog/kleines-buero-mieten-traun-checkliste" : "/blog/flexplatz-oder-fester-schreibtisch"} className="mt-3 block py-3 text-emerald-800 underline underline-offset-4">{office ? "Checkliste: Worauf du bei einem kleinen Büro achten solltest" : "Flex oder Fix? Die Unterschiede im Überblick"}</Link></section>
  </MarketingPage>;
}
